In [1]:
import pandas as pd

df = pd.read_csv("songs_with_lyrics.csv")

print(df.head())

                    Artist                    Song       Key  BPM Camelot  \
0                21 Savage            ball w/o you  A♭ Major  138      4B
1                21 Savage  can't leave without it  F# Minor  132     11A
2  21 Savage, Metro Boomin         Glock In My Lap  B♭ Minor  130      3A
3  21 Savage, Metro Boomin                 Feel It  C# Minor  150     12A
4                     22Gz             Retaliation   B Major  142      1B

   Popularity  Energy  Danceability  Hapiness  \
0          80      63            89        46
1          74      59            87        70
2          80      73            85        20
3          49      45            76        30
4          55      68            92        49

                                              lyrics
0  Woah\nWoah, woah\n\nYou runnin' 'round drinkin...
1  Yeah\n\nVVS look like a star (Yeah)\nI took th...
2  Y'all niggas stop playin', nigga\nY'all niggas...
3  “Feel It” is the eighth track off of the colla...
4  (SkinnyKhris)\nSkrrt, skrrt\nSkrrt, skrrt, skr...

In [2]:
# Replace 'lyrics' with the actual column name if different
missing_lyrics = df[df['lyrics'].isnull() | (df['lyrics'].str.strip() == '')]

# Display those rows
print(missing_lyrics)

                              Artist                               Song  \
11    3 Doors Down, Jack Joseph Puig                          Let Me Go
16    3OH!3, Katy Perry, Matt Squire      STARSTRUKK (feat. Katy Perry)
40               A Flock Of Seagulls  I Ran (So Far Away) - Single Edit
53      Ace DJ Xquisite, Zaki Amujei          Dorime - Amapiano Version
67                 Alanis Morissette     Head over Feet - 2015 Remaster
...                              ...                                ...
2080                 Young the Giant            My Body - 2020 Remaster
2092             Yusuf / Cat Stevens      Peace Train - Remastered 2021
2111                   Zedd, Kehlani          Good Thing (with Kehlani)
2117                           Zolik                     Like a Brother
2118                          ZZ Top          La Grange (2005 Remaster)

           Key  BPM Camelot  Popularity  Energy  Danceability  Hapiness lyrics
11    C# Minor   92     12A          64      86            48        49    NaN
16     B Minor  140     10A          68      81            61        23    NaN
40     D Major  146     10B          66      77            51        64    NaN
53    C# Major  115      3B          23      64            93        76    NaN
67     C Major   80      8B          68      81            48        44    NaN
...        ...  ...     ...         ...     ...           ...       ...    ...
2080  B♭ Major  130      6B          62      90            49        53    NaN
2092   C Major   82      8B          69      68            59        76    NaN
2111  C# Minor  186     12A          66      56            69        57    NaN
2117  E♭ Major  184      5B          46      39            11        14    NaN
2118   E Minor  162      9A          82      64            51        61    NaN

[260 rows x 10 columns]

In [3]:
# Remove rows where lyrics are NaN or just empty/whitespace
df = df[~(df['lyrics'].isnull() | (df['lyrics'].str.strip() == ''))]

# Optionally, reset the index
df = df.reset_index(drop=True)

In [4]:
df

,Artist,Song,Key,BPM,Camelot,Popularity,Energy,Danceability,Hapiness,lyrics
0,21 Savage,ball w/o you,A♭ Major,138,4B,80,63,89,46,"Woah\nWoah, woah\n\nYou runnin' 'round drinkin..."
1,21 Savage,can't leave without it,F# Minor,132,11A,74,59,87,70,Yeah\n\nVVS look like a star (Yeah)\nI took th...
2,"21 Savage, Metro Boomin",Glock In My Lap,B♭ Minor,130,3A,80,73,85,20,"Y'all niggas stop playin', nigga\nY'all niggas..."
3,"21 Savage, Metro Boomin",Feel It,C# Minor,150,12A,49,45,76,30,“Feel It” is the eighth track off of the colla...
4,22Gz,Retaliation,B Major,142,1B,55,68,92,49,"(SkinnyKhris)\nSkrrt, skrrt\nSkrrt, skrrt, skr..."
...,...,...,...,...,...,...,...,...,...,...
1854,"Zedd, Maren Morris, Grey",The Middle,G Major,107,9B,81,66,75,44,"One, two, egg!\n\nTake a seat\nRight over ther..."
1855,ZEROBASEONE,KILL THE ROMEO,B Minor,123,10A,49,93,70,76,Na-na-na-na-na-na\nNa-na-na-na-na-na\nNa-na-na...
1856,ZEROBASEONE,Doctor! Doctor!,B♭ Major,88,6B,59,68,64,61,"Doctor, doctor, help me\n낫게 해줘 너 때문인 lovesick\..."
1857,ZEROBASEONE,GOOD SO BAD,C# Major,110,3B,54,74,73,82,When you hear the rhythm\nStart to move\n\nMak...
1858,Ziggy Alberts,Runaway,F Major,110,7B,67,50,75,51,"You see well, I remember how you said\nThat so..."

In [6]:
from langdetect import detect, DetectorFactory
from langdetect.lang_detect_exception import LangDetectException

# Make language detection deterministic (same result every time)
DetectorFactory.seed = 0

# Function to detect language safely
def detect_language(text):
    try:
        return detect(text)
    except LangDetectException:
        return 'error'

# Apply to the lyrics column (this may take some time with 2000+ songs)
df['language'] = df['lyrics'].apply(detect_language)

# Check how many are not English
non_english_df = df[df['language'] != 'en']

# Show some examples
print(non_english_df[['Song', 'Artist', 'language']].head())

                                     Song                            Artist  \
28  MAMA (feat. Nicki Minaj & Kanye West)  6ix9ine, Kanye West, Nicki Minaj
34                                TIC TAC                             8TURN
49           Listo Para Nuestro Encuentro                       Abel Zavala
51             2 die 4 (feat. Charli XCX)           Addison Rae, Charli xcx
54                               No Estoy            AFTER, Milo j, Akim 88

   language
28       pt
34       tl
49       es
51       es
54       es

In [8]:
non_english_df

,Artist,Song,Key,BPM,Camelot,Popularity,Energy,Danceability,Hapiness,lyrics,language
28,"6ix9ine, Kanye West, Nicki Minaj",MAMA (feat. Nicki Minaj & Kanye West),C# Major,160,3B,57,66,76,44,Uh\nMurda on the beat so it's not nice!\n\nTik...,pt
34,8TURN,TIC TAC,D Major,89,10B,51,94,73,77,"Ooh\nOoh\n\n찌릿찌릿해 맘을 스친 꿈이\n끼리끼리, yeah, 우린 뼛속까...",tl
49,Abel Zavala,Listo Para Nuestro Encuentro,C# Major,115,3B,57,24,45,20,Vivo cada día esperándote\nTal como la novia a...,es
51,"Addison Rae, Charli xcx",2 die 4 (feat. Charli XCX),B♭ Minor,105,3A,65,59,86,43,"Lejos de casa, me estoy acercando\nY la música...",es
54,"AFTER, Milo j, Akim 88",No Estoy,G Major,120,9B,63,66,83,70,"Je-eh\nAfter, tomate un mate (El M), yeah, yea...",es
...,...,...,...,...,...,...,...,...,...,...,...
1739,TWICE,CHEER UP,F# Major,173,2B,54,89,55,51,"매일 울리는 벨, 벨, 벨\n이젠 나를 배려 해줘\n배터리 낭비하긴 싫어\n자꾸만 ...",ko
1744,"Ty Dolla $ign, Post Malone",Spicy (feat. Post Malone),E Minor,100,9A,65,51,78,12,"(James, kahretsin)\n(Dolla $ign, Dolla $ign)\n...",tr
1813,"Yebba, A$AP Rocky",Far Away (feat. A$AP Rocky),F# Minor,88,11A,70,58,69,23,"Enrolo todos os meus, arrisco minhas chances\n...",pt
1826,"Young Thug, Lil Baby",Bad Bad Bad (feat. Lil Baby),F# Major,112,2B,82,60,97,89,Wheezy na área\n\nAssentos de ouro rosa na por...,pt
1828,"YSY A, Bhavi, Duki",SONIDO DEL AÑO,F Minor,174,4A,60,73,61,94,"Yeah, YSY, Duko, Bhavi (雪山, 吃飯啦!)\n\nAncho de ...",es

In [9]:
# Keep only songs where the detected language is English ('en')
df = df[df['language'] == 'en'].reset_index(drop=True)

In [10]:
df

,Artist,Song,Key,BPM,Camelot,Popularity,Energy,Danceability,Hapiness,lyrics,language
0,21 Savage,ball w/o you,A♭ Major,138,4B,80,63,89,46,"Woah\nWoah, woah\n\nYou runnin' 'round drinkin...",en
1,21 Savage,can't leave without it,F# Minor,132,11A,74,59,87,70,Yeah\n\nVVS look like a star (Yeah)\nI took th...,en
2,"21 Savage, Metro Boomin",Glock In My Lap,B♭ Minor,130,3A,80,73,85,20,"Y'all niggas stop playin', nigga\nY'all niggas...",en
3,"21 Savage, Metro Boomin",Feel It,C# Minor,150,12A,49,45,76,30,“Feel It” is the eighth track off of the colla...,en
4,22Gz,Retaliation,B Major,142,1B,55,68,92,49,"(SkinnyKhris)\nSkrrt, skrrt\nSkrrt, skrrt, skr...",en
...,...,...,...,...,...,...,...,...,...,...,...
1705,"Zedd, Maren Morris, Grey",The Middle,G Major,107,9B,81,66,75,44,"One, two, egg!\n\nTake a seat\nRight over ther...",en
1706,ZEROBASEONE,KILL THE ROMEO,B Minor,123,10A,49,93,70,76,Na-na-na-na-na-na\nNa-na-na-na-na-na\nNa-na-na...,en
1707,ZEROBASEONE,Doctor! Doctor!,B♭ Major,88,6B,59,68,64,61,"Doctor, doctor, help me\n낫게 해줘 너 때문인 lovesick\...",en
1708,ZEROBASEONE,GOOD SO BAD,C# Major,110,3B,54,74,73,82,When you hear the rhythm\nStart to move\n\nMak...,en
1709,Ziggy Alberts,Runaway,F Major,110,7B,67,50,75,51,"You see well, I remember how you said\nThat so...",en

In [11]:
df.to_csv('final_dataset.csv', index=False)